name: "CONFIG COLLECTOR"

on:
  workflow_dispatch:
  schedule:
    - cron: '*/480 * * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Execute PHP script
        run: |
          php bot.php
          git config credential.helper store
      
      - name: Configure Git
        run: |
          git config --global user.email "tonyzhang1995@gmail.com"
          git config --global user.name "zyjia"
          git remote set-url origin https://github.com/zyjia/V2rayCollector.git
      
      - name: Push changes with rebase
        run: |
          git add -A
          git commit -m "🌩 New Servers Added - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
          git pull --rebase origin main
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_BOT }}

